layout: page
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
kramdown:
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3

include: documentation.md

